project:
    type: website
    output-dir: docs # cambiar carpeta donde se construye el sitio

website:
  description: "mi primer blog"
  site-url: https://jvet2622.github.io/prueba_blog
  title: "prueba_blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jvet2622/prueba_blog
      - icon: bluesky
        href: https://bsky.app/
format:
  html:
    theme:
      - Simplex
      - brand
      - tema.scss
    css: styles.css



